local spr = Sprite(64, 64, ColorMode.RGB)
app.activeSprite = spr
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_00.png")
spr.cels[1].image:clear()
spr.cels[1].image = src.cels[1].image:clone()
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_01.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_02.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_03.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_04.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_05.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_06.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_07.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_08.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_09.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_10.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_11.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_12.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_13.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_14.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_15.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_16.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_17.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_18.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
local src = app.open("D:/Github/FinalProject/aseprite_work/frames/run_stop_19.png")
local fr = spr:newEmptyFrame()
spr:newCel(spr.layers[1], fr, src.cels[1].image:clone(), Point(0,0))
src:close()
spr:saveAs("D:/Github/FinalProject/aseprite_work/character_run_stop.aseprite")
app.exit()